// Tests for arch-map.mjs -- portable architecture-map hook that renders debt-gate.mjs's --graph
// dump into docs/ARCH-MAP.md (Mermaid + 80/20 index). Zero-dep: Node built-in test runner.
// Run:  node --test arch-map.test.mjs
import { test } from "node:test";
import assert from "node:assert/strict";
import * as fs from "node:fs";
import * as os from "node:os";
import * as path from "node:path";
import { spawnSync } from "node:child_process";
import { fileURLToPath } from "node:url";

const HERE = path.dirname(fileURLToPath(import.meta.url));
const RUNNER = path.join(HERE, "template", "arch-map.mjs");
const REAL_GATE = path.join(HERE, "template", "debt-gate.mjs");

function tmp() {
  return fs.mkdtempSync(path.join(os.tmpdir(), "archmap-"));
}
function run(args, env = {}) {
  const r = spawnSync(process.execPath, [RUNNER, ...args], {
    encoding: "utf8",
    env: { ...process.env, ...env },
  });
  return { status: r.status, stdout: r.stdout, stderr: r.stderr };
}
function writeFile(dir, rel, content) {
  const p = path.join(dir, rel);
  fs.mkdirSync(path.dirname(p), { recursive: true });
  fs.writeFileSync(p, content);
  return p;
}
function writeConfig(dir, config) {
  writeFile(dir, path.join(".pm", "debt-gate.json"), JSON.stringify(config, null, 2));
}

// A two-layer fixture that debt-gate.mjs will report config:"ok" for -- also used as the smoke
// fixture referenced in the build report.
function twoLayerFixture() {
  const d = tmp();
  writeConfig(d, {
    declared: "yes",
    layers: [
      { name: "ui", paths: ["ui"] },
      { name: "core", paths: ["core"] },
    ],
    forbidden_edges: [],
    entry: {},
    thresholds: {},
    allow: [],
  });
  writeFile(d, "ui/widget.ts", "export const widget = 1;\n");
  writeFile(d, "core/thing.ts", "import { widget } from '../ui/widget';\nexport const y = widget;\n");
  writeFile(d, path.join(".pm", "CONTRACTS.md"), "## ui\n## core\n");
  return d;
}

// ---------------------------------------------------------------------------
// 1. missing root -> exit 1

test("missing root -> exit 1, stderr names the missing path", () => {
  const missing = path.join(tmp(), "does-not-exist-xyz");
  const r = run([missing]);
  assert.equal(r.status, 1, r.stdout);
  assert.match(r.stderr, /does-not-exist-xyz/);
});

// ---------------------------------------------------------------------------
// 2. schema-mismatch fail-closed: point a copy of arch-map.mjs at a fake sibling gate that does
// not understand --graph (predates the feature / prints junk).

function buildFakeHooksDir(gateBody) {
  const hooksDir = fs.mkdtempSync(path.join(os.tmpdir(), "archmap-fakehooks-"));
  fs.copyFileSync(RUNNER, path.join(hooksDir, "arch-map.mjs"));
  fs.writeFileSync(path.join(hooksDir, "debt-gate.mjs"), gateBody);
  return path.join(hooksDir, "arch-map.mjs");
}

test("schema mismatch (fake gate prints junk, no --graph support) -> fail-closed exit 1", () => {
  const fakeRunner = buildFakeHooksDir("#!/usr/bin/env node\nprocess.stdout.write('not json at all');\nprocess.exit(0);\n");
  const d = twoLayerFixture();
  const r = spawnSync(process.execPath, [fakeRunner, d], { encoding: "utf8" });
  assert.equal(r.status, 1, r.stdout);
  assert.match(r.stderr, /predates --graph/);
});

test("schema mismatch (fake gate emits valid JSON but wrong schema tag) -> fail-closed exit 1", () => {
  const fakeRunner = buildFakeHooksDir(
    "#!/usr/bin/env node\nprocess.stdout.write(JSON.stringify({schema:'something-else/1'}));\nprocess.exit(0);\n"
  );
  const d = twoLayerFixture();
  const r = spawnSync(process.execPath, [fakeRunner, d], { encoding: "utf8" });
  assert.equal(r.status, 1, r.stdout);
  assert.match(r.stderr, /predates --graph/);
});

// ---------------------------------------------------------------------------
// 3. default write: docs/ARCH-MAP.md with GENERATED header + graph-hash

test("default mode writes docs/ARCH-MAP.md with GENERATED header + graph-hash", () => {
  const d = twoLayerFixture();
  const r = run([d]);
  assert.equal(r.status, 0, r.stderr + r.stdout);
  const outPath = path.join(d, "docs", "ARCH-MAP.md");
  assert.ok(fs.existsSync(outPath));
  const text = fs.readFileSync(outPath, "utf8");
  assert.match(text, /^<!-- GENERATED by \.pm\/hooks\/arch-map\.mjs -- DO NOT EDIT -- graph-hash: [0-9a-f]{64} -- unresolved imports: \d+ -->/);
  assert.match(text, /# Architecture Map/);
  assert.match(text, /## Module map/);
  assert.match(text, /```mermaid/);
});

// ---------------------------------------------------------------------------
// 4. --check: exit 2 when missing/stale, 0 when fresh

test("--check: exit 2 when docs/ARCH-MAP.md is missing", () => {
  const d = twoLayerFixture();
  const r = run([d, "--check"]);
  assert.equal(r.status, 2, r.stdout);
  assert.match(r.stdout, /MISSING/);
});

test("--check: exit 2 when docs/ARCH-MAP.md is stale, 0 once regenerated", () => {
  const d = twoLayerFixture();
  const outPath = path.join(d, "docs", "ARCH-MAP.md");
  writeFile(d, path.join("docs", "ARCH-MAP.md"), "stale content\n");
  const rStale = run([d, "--check"]);
  assert.equal(rStale.status, 2, rStale.stdout);
  assert.match(rStale.stdout, /STALE/);

  const rWrite = run([d]);
  assert.equal(rWrite.status, 0, rWrite.stderr + rWrite.stdout);

  const rFresh = run([d, "--check"]);
  assert.equal(rFresh.status, 0, rFresh.stdout);
  assert.match(rFresh.stdout, /fresh/);
  assert.ok(fs.existsSync(outPath));
});

// ---------------------------------------------------------------------------
// 5. deterministic output: two independent writes are byte-identical

test("deterministic: running twice on the SAME fixture produces byte-identical docs/ARCH-MAP.md", () => {
  const d = twoLayerFixture();
  const r1 = run([d]);
  const t1 = fs.readFileSync(path.join(d, "docs", "ARCH-MAP.md"), "utf8");
  const r2 = run([d]);
  const t2 = fs.readFileSync(path.join(d, "docs", "ARCH-MAP.md"), "utf8");
  assert.equal(r1.status, 0, r1.stderr);
  assert.equal(r2.status, 0, r2.stderr);
  assert.equal(t1, t2);
});

test("deterministic: --stdout run twice on the same fixture is byte-identical", () => {
  const d = twoLayerFixture();
  const r1 = run([d, "--stdout"]);
  const r2 = run([d, "--stdout"]);
  assert.equal(r1.status, 0, r1.stderr);
  assert.equal(r2.status, 0, r2.stderr);
  assert.equal(r1.stdout, r2.stdout);
});

// ---------------------------------------------------------------------------
// 6. DEBT_GATE_STRICT=1 in the parent env must NOT make arch-map fail (it deletes it for the child)

test("DEBT_GATE_STRICT=1 in environment does not make arch-map fail", () => {
  const d = twoLayerFixture();
  const r = run([d, "--stdout"], { DEBT_GATE_STRICT: "1" });
  assert.equal(r.status, 0, r.stderr + r.stdout);
  assert.match(r.stdout, /# Architecture Map/);
});

// ---------------------------------------------------------------------------
// 7. module-level collapse when layers declared

test("module-level collapse: file nodes collapse to declared layer nodes, edge aggregated with count", () => {
  const d = twoLayerFixture();
  const r = run([d, "--stdout"]);
  assert.equal(r.status, 0, r.stderr + r.stdout);
  assert.match(r.stdout, /Config state: \*\*ok\*\*/);
  assert.match(r.stdout, /"ui \(1 file\)"/);
  assert.match(r.stdout, /"core \(1 file\)"/);
  // aggregated layer->layer edge with a count label (core imports ui)
  assert.match(r.stdout, /-->\|1\|/);
  // small fixture (<=60 nodes) + config ok -> file-level section also present
  assert.match(r.stdout, /## File map/);
});

test("undeclared config: groups by top-level directory instead of layer", () => {
  const d = tmp();
  writeFile(d, "srcA/one.ts", "export const one = 1;\n");
  writeFile(d, "srcB/two.ts", "import { one } from '../srcA/one';\nexport const two = one;\n");
  const r = run([d, "--stdout"]);
  assert.equal(r.status, 0, r.stderr + r.stdout);
  assert.match(r.stdout, /Config state: \*\*missing\*\*/);
  assert.match(r.stdout, /"srcA \(1 file\)"/);
  assert.match(r.stdout, /"srcB \(1 file\)"/);
  // no file-level section when config is not "ok"
  assert.ok(!/## File map/.test(r.stdout));
});
